assert 'foo' > 1; // #error #exception
return 0;
